appName: cart
replicaCount: 1
image:
  repository: 378784712135.dkr.ecr.us-east-1.amazonaws.com/cart
  pullPolicy: Always

env:
  name: prod

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}

service:
  type: ClusterIP
  port: 80
  containerPort: 8080

resources:
  limits:
    cpu: 100m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 256Mi

configmap:
  create: true
  content:
    REDIS_HOST: redis-master
    CATALOGUE_HOST: catalogue
    CATALOGUE_PORT: "80"

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70